<?php

class ProjectsTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('projects')->truncate();
        
		\DB::table('projects')->insert(array (
			0 => 
			array (
				'id' => 1,
				'client_id' => 3,
				'contact_id' => 3,
				'name' => 'Spring Check Email',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Simon (FE), Danny',
				'phase_id' => 8,
				'percentage_complete' => 0,
				'estimate_number' => '950',
				'estimate_link' => 'https://diginutltd.freeagent.com/projects/564563/invoices',
				'estimate_phase' => NULL,
				'value' => '300.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 13:44:40',
				'updated_at' => '2014-04-10 14:16:12',
			),
			1 => 
			array (
				'id' => 2,
				'client_id' => 9,
				'contact_id' => 8,
				'name' => 'March Newsletter',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => 'Alex',
				'phase_id' => 8,
				'percentage_complete' => 100,
				'estimate_number' => '959',
				'estimate_link' => 'https://diginutltd.freeagent.com/invoices/8606567',
				'estimate_phase' => 'Invoiced',
				'value' => '288.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 13:55:11',
				'updated_at' => '2014-04-09 13:55:11',
			),
			2 => 
			array (
				'id' => 3,
				'client_id' => 15,
				'contact_id' => 11,
				'name' => 'Cue & Co CMS',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 8,
				'percentage_complete' => 100,
				'estimate_number' => '934',
				'estimate_link' => 'https://diginutltd.freeagent.com/invoices/8351403',
				'estimate_phase' => NULL,
				'value' => '15500.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:04:45',
				'updated_at' => '2014-04-09 14:04:45',
			),
			3 => 
			array (
				'id' => 4,
				'client_id' => 5,
				'contact_id' => 7,
				'name' => 'Coppafeel Post Launch Amends',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Alex (BE)',
				'phase_id' => 8,
				'percentage_complete' => 100,
				'estimate_number' => '946',
				'estimate_link' => 'https://diginutltd.freeagent.com/invoices/8542730',
				'estimate_phase' => 'Paid',
				'value' => '777.60',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:06:39',
				'updated_at' => '2014-04-09 14:06:39',
			),
			4 => 
			array (
				'id' => 5,
				'client_id' => 9,
				'contact_id' => 10,
				'name' => 'Nissan Trade Email April - x5',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Simon (BE), Danny',
				'phase_id' => 8,
				'percentage_complete' => 100,
				'estimate_number' => '880',
				'estimate_link' => 'https://diginutltd.freeagent.com/estimates/542398',
				'estimate_phase' => 'Invoiced',
				'value' => '1740.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:08:00',
				'updated_at' => '2014-04-09 14:08:00',
			),
			5 => 
			array (
				'id' => 6,
				'client_id' => 4,
				'contact_id' => 6,
				'name' => 'Virgin Money - Extramile',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Pete (FE), Julian (BE)',
				'phase_id' => 5,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => NULL,
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:10:47',
				'updated_at' => '2014-04-09 14:10:47',
			),
			6 => 
			array (
				'id' => 7,
				'client_id' => 7,
				'contact_id' => 10,
				'name' => 'Ibiza Rocks',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 4,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => NULL,
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:11:01',
				'updated_at' => '2014-04-09 14:11:11',
			),
			7 => 
			array (
				'id' => 8,
				'client_id' => 8,
				'contact_id' => 5,
				'name' => 'Dinner Set',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Anh (Design), Pete (FE), Simon (BE)',
				'phase_id' => 4,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => NULL,
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:31:11',
				'updated_at' => '2014-04-09 14:31:11',
			),
			8 => 
			array (
				'id' => 9,
				'client_id' => 14,
				'contact_id' => 15,
				'name' => 'Centria',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Pete (FE), Simon (BE)',
				'phase_id' => 5,
				'percentage_complete' => 80,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => NULL,
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:31:45',
				'updated_at' => '2014-04-10 13:27:59',
			),
			9 => 
			array (
				'id' => 10,
				'client_id' => 3,
				'contact_id' => 4,
				'name' => 'Nissan Trade Email April - x3',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Simone (BE), Danny',
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => NULL,
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:32:25',
				'updated_at' => '2014-04-09 14:32:25',
			),
			10 => 
			array (
				'id' => 11,
				'client_id' => 3,
				'contact_id' => 4,
				'name' => 'Nissan eNewsletter',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Simon (BE), Danny',
				'phase_id' => 5,
				'percentage_complete' => 75,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => NULL,
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:33:05',
				'updated_at' => '2014-04-09 14:33:05',
			),
			11 => 
			array (
				'id' => 12,
				'client_id' => 12,
				'contact_id' => 10,
				'name' => 'Causeway Finance Web App',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Pete (FE), Julian (BE)',
				'phase_id' => 5,
				'percentage_complete' => 50,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '11500.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:35:00',
				'updated_at' => '2014-04-09 14:35:00',
			),
			12 => 
			array (
				'id' => 13,
				'client_id' => 11,
				'contact_id' => 9,
				'name' => 'Imbruvica iRep App',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => 'Simon',
				'phase_id' => 3,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => NULL,
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:36:01',
				'updated_at' => '2014-04-09 14:36:01',
			),
			13 => 
			array (
				'id' => 14,
				'client_id' => 6,
				'contact_id' => 1,
				'name' => 'Samsung SSD',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '23148.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:38:28',
				'updated_at' => '2014-04-09 14:38:28',
			),
			14 => 
			array (
				'id' => 15,
				'client_id' => 10,
				'contact_id' => 21,
				'name' => 'Lima Websites',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 80,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '6912.00',
				'estimated_development_time' => 80,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:53:27',
				'updated_at' => '2014-04-09 14:53:27',
			),
			15 => 
			array (
				'id' => 16,
				'client_id' => 11,
				'contact_id' => 14,
				'name' => 'Siltuximab 1',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => NULL,
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:56:28',
				'updated_at' => '2014-04-09 14:56:28',
			),
			16 => 
			array (
				'id' => 17,
				'client_id' => 11,
				'contact_id' => 22,
				'name' => 'Siltuximab 1',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '6048.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:57:53',
				'updated_at' => '2014-04-09 14:57:53',
			),
			17 => 
			array (
				'id' => 18,
				'client_id' => 11,
				'contact_id' => 22,
				'name' => 'Siltuximab 2',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '6048.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:58:09',
				'updated_at' => '2014-04-09 14:58:09',
			),
			18 => 
			array (
				'id' => 19,
				'client_id' => 11,
				'contact_id' => 22,
				'name' => 'Siltuximab 3',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '6912.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:58:34',
				'updated_at' => '2014-04-09 14:58:34',
			),
			19 => 
			array (
				'id' => 20,
				'client_id' => 11,
				'contact_id' => 22,
				'name' => 'Siltuximab 4',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '3744.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:58:56',
				'updated_at' => '2014-04-09 14:58:56',
			),
			20 => 
			array (
				'id' => 21,
				'client_id' => 11,
				'contact_id' => 22,
				'name' => 'Imbruvica 1',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '20952.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:59:36',
				'updated_at' => '2014-04-09 14:59:36',
			),
			21 => 
			array (
				'id' => 22,
				'client_id' => 11,
				'contact_id' => 22,
				'name' => 'Imbruvica 2',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '8064.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:59:55',
				'updated_at' => '2014-04-09 14:59:55',
			),
			22 => 
			array (
				'id' => 23,
				'client_id' => 4,
				'contact_id' => 6,
				'name' => 'Extramile YouTube',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 100,
				'resource' => NULL,
				'phase_id' => 7,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '6336.00',
				'estimated_development_time' => 40,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 15:01:10',
				'updated_at' => '2014-04-10 13:29:32',
			),
			23 => 
			array (
				'id' => 24,
				'client_id' => 1,
				'contact_id' => 23,
				'name' => 'Sky Bundle App',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 50,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '29376.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 15:04:41',
				'updated_at' => '2014-04-09 15:04:41',
			),
			24 => 
			array (
				'id' => 25,
				'client_id' => 12,
				'contact_id' => 10,
				'name' => 'Hosting',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 50,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '1822.80',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 15:05:22',
				'updated_at' => '2014-04-09 15:05:22',
			),
			25 => 
			array (
				'id' => 26,
				'client_id' => 13,
				'contact_id' => 14,
				'name' => 'Wordpress Update',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 50,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '2484.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 15:06:12',
				'updated_at' => '2014-04-09 15:06:12',
			),
			26 => 
			array (
				'id' => 27,
				'client_id' => 2,
				'contact_id' => 24,
				'name' => 'Start JG Phase II Updates',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 75,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => '900',
				'estimate_link' => 'https://diginutltd.freeagent.com/estimates/562618',
				'estimate_phase' => NULL,
				'value' => '8064.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 15:06:45',
				'updated_at' => '2014-04-10 13:42:47',
			),
			27 => 
			array (
				'id' => 28,
				'client_id' => 16,
				'contact_id' => 16,
				'name' => 'Cavo Alkyoni Website',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '1890.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 15:08:30',
				'updated_at' => '2014-04-09 15:08:30',
			),
			28 => 
			array (
				'id' => 29,
				'client_id' => 5,
				'contact_id' => 7,
				'name' => 'Coppafeel SMS sign up updates',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 50,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '880.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 09:24:22',
				'updated_at' => '2014-04-10 09:24:22',
			),
			29 => 
			array (
				'id' => 30,
				'client_id' => 3,
				'contact_id' => 4,
				'name' => 'Nissan FPS HTML Email',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 80,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => '894',
				'estimate_link' => 'https://diginutltd.freeagent.com/estimates/554713',
				'estimate_phase' => NULL,
				'value' => '3120.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 09:26:24',
				'updated_at' => '2014-04-10 09:26:24',
			),
			30 => 
			array (
				'id' => 31,
				'client_id' => 17,
				'contact_id' => 17,
				'name' => 'Mobile Website & App',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '55000.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 09:26:56',
				'updated_at' => '2014-04-10 09:26:56',
			),
			31 => 
			array (
				'id' => 32,
				'client_id' => 2,
				'contact_id' => 18,
				'name' => 'Adidas CRP Site amends',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 50,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => '895',
				'estimate_link' => 'https://diginutltd.freeagent.com/estimates/557153',
				'estimate_phase' => NULL,
				'value' => '7632.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 09:27:38',
				'updated_at' => '2014-04-10 09:27:38',
			),
			32 => 
			array (
				'id' => 33,
				'client_id' => 11,
				'contact_id' => 25,
				'name' => 'Vfend iRep Detail Aid',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 60,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '8400.00',
				'estimated_development_time' => 160,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 09:28:03',
				'updated_at' => '2014-04-10 09:30:46',
			),
			33 => 
			array (
				'id' => 34,
				'client_id' => 19,
				'contact_id' => 19,
				'name' => 'IOVOX Reseller Platform',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 50,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '17568.00',
				'estimated_development_time' => 160,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 09:29:23',
				'updated_at' => '2014-04-10 09:31:15',
			),
			34 => 
			array (
				'id' => 35,
				'client_id' => 18,
				'contact_id' => 20,
				'name' => 'Interim Design Refresh',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '5472.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 09:29:53',
				'updated_at' => '2014-04-10 09:29:53',
			),
			35 => 
			array (
				'id' => 36,
				'client_id' => 20,
				'contact_id' => 26,
				'name' => 'Brand App',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => NULL,
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 12:38:45',
				'updated_at' => '2014-04-10 12:38:45',
			),
		));
	}

}
