<?php

class ProjectsTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('projects')->truncate();
        
		\DB::table('projects')->insert(array (
			0 => 
			array (
				'id' => 1,
				'client_id' => 3,
				'contact_id' => 3,
				'name' => 'Spring Check Email',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Simon (FE), Danny',
				'phase_id' => 8,
				'percentage_complete' => 100,
				'estimate_number' => '950',
				'estimate_link' => 'https://diginutltd.freeagent.com/projects/564563/invoices',
				'estimate_phase' => '12',
				'value' => '300.00',
				'estimated_development_time' => 5,
				'actual_development_time' => 4,
				'completed_date' => '2014-03-27',
				'created_at' => '2014-04-09 13:44:40',
				'updated_at' => '2014-04-16 13:26:52',
			),
			1 => 
			array (
				'id' => 2,
				'client_id' => 9,
				'contact_id' => 8,
				'name' => 'March Newsletter',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => 'Alex',
				'phase_id' => 8,
				'percentage_complete' => 0,
				'estimate_number' => '959',
				'estimate_link' => 'https://diginutltd.freeagent.com/invoices/8606567',
				'estimate_phase' => 'Invoiced',
				'value' => '288.00',
				'estimated_development_time' => 4,
				'actual_development_time' => 6,
				'completed_date' => '2014-03-27',
				'created_at' => '2014-04-09 13:55:11',
				'updated_at' => '2014-04-16 13:25:48',
			),
			2 => 
			array (
				'id' => 3,
				'client_id' => 15,
				'contact_id' => 11,
				'name' => 'Cue & Co CMS',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 8,
				'percentage_complete' => 100,
				'estimate_number' => '934',
				'estimate_link' => 'https://diginutltd.freeagent.com/invoices/8351403',
				'estimate_phase' => NULL,
				'value' => '15500.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => '2014-03-21',
				'created_at' => '2014-04-09 14:04:45',
				'updated_at' => '2014-04-17 14:49:43',
			),
			3 => 
			array (
				'id' => 4,
				'client_id' => 5,
				'contact_id' => 7,
				'name' => 'Coppafeel Post Launch Amends',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Alex (BE)',
				'phase_id' => 8,
				'percentage_complete' => 0,
				'estimate_number' => '946',
				'estimate_link' => 'https://diginutltd.freeagent.com/invoices/8542730',
				'estimate_phase' => 'Paid',
				'value' => '777.60',
				'estimated_development_time' => 12,
				'actual_development_time' => 8,
				'completed_date' => '2014-03-24',
				'created_at' => '2014-04-09 14:06:39',
				'updated_at' => '2014-04-16 13:48:39',
			),
			4 => 
			array (
				'id' => 5,
				'client_id' => 9,
				'contact_id' => 10,
				'name' => 'Nissan Trade Email April - x5',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Simon (BE), Danny',
				'phase_id' => 8,
				'percentage_complete' => 0,
				'estimate_number' => '880',
				'estimate_link' => 'https://diginutltd.freeagent.com/estimates/542398',
				'estimate_phase' => 'Invoiced',
				'value' => '1740.00',
				'estimated_development_time' => 29,
				'actual_development_time' => 29,
				'completed_date' => '2014-03-31',
				'created_at' => '2014-04-09 14:08:00',
				'updated_at' => '2014-04-17 14:49:57',
			),
			5 => 
			array (
				'id' => 6,
				'client_id' => 4,
				'contact_id' => 6,
				'name' => 'Virgin Money - Extramile',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Pete (FE), Julian (BE)',
				'phase_id' => 5,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => NULL,
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:10:47',
				'updated_at' => '2014-04-12 07:37:33',
			),
			6 => 
			array (
				'id' => 7,
				'client_id' => 7,
				'contact_id' => 10,
				'name' => 'Ibiza Rocks',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 4,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '22752.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:11:01',
				'updated_at' => '2014-04-17 15:08:33',
			),
			7 => 
			array (
				'id' => 8,
				'client_id' => 8,
				'contact_id' => 5,
				'name' => 'Dinner Set',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Anh (Design), Pete (FE), Simon (BE)',
				'phase_id' => 4,
				'percentage_complete' => 10,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => NULL,
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:31:11',
				'updated_at' => '2014-04-17 10:34:47',
			),
			8 => 
			array (
				'id' => 9,
				'client_id' => 14,
				'contact_id' => 15,
				'name' => 'Centria',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Pete (FE), Simon (BE)',
				'phase_id' => 5,
				'percentage_complete' => 80,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => NULL,
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:31:45',
				'updated_at' => '2014-04-10 13:27:59',
			),
			9 => 
			array (
				'id' => 10,
				'client_id' => 3,
				'contact_id' => 4,
			'name' => 'Nissan Trade Campaign (May to September) Emails x 3 - Brake pads & discs',
				'start_date' => NULL,
				'due_date' => '2014-04-23',
				'golive_date' => '2014-04-23',
				'likelihood' => 100,
			'resource' => 'Simon (BE), Danny',
				'phase_id' => 2,
				'percentage_complete' => 0,
				'estimate_number' => '881',
				'estimate_link' => 'https://diginutltd.freeagent.com/estimates/542407',
				'estimate_phase' => 'Build',
				'value' => '379.99',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:32:25',
				'updated_at' => '2014-04-22 12:40:47',
			),
			10 => 
			array (
				'id' => 11,
				'client_id' => 3,
				'contact_id' => 4,
				'name' => 'Nissan eNewsletter',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Simon (BE), Danny',
				'phase_id' => 5,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '480.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:33:05',
				'updated_at' => '2014-04-17 15:07:08',
			),
			11 => 
			array (
				'id' => 12,
				'client_id' => 12,
				'contact_id' => 10,
				'name' => 'Causeway Finance Web App',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Pete (FE), Julian (BE)',
				'phase_id' => 5,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '11088.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:35:00',
				'updated_at' => '2014-04-17 15:37:09',
			),
			12 => 
			array (
				'id' => 13,
				'client_id' => 11,
				'contact_id' => 9,
				'name' => 'Imbruvica iRep App',
				'start_date' => NULL,
				'due_date' => '2014-05-16',
				'golive_date' => NULL,
				'likelihood' => NULL,
			'resource' => 'Simon (BE), Pete (FE)',
				'phase_id' => 4,
				'percentage_complete' => 0,
				'estimate_number' => '850',
				'estimate_link' => 'https://diginutltd.freeagent.com/estimates/506635',
				'estimate_phase' => NULL,
				'value' => '20952.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:36:01',
				'updated_at' => '2014-04-22 08:22:52',
			),
			13 => 
			array (
				'id' => 14,
				'client_id' => 6,
				'contact_id' => 1,
				'name' => 'Samsung SSD',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 10,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '23148.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:38:28',
				'updated_at' => '2014-04-11 13:06:33',
			),
			14 => 
			array (
				'id' => 15,
				'client_id' => 10,
				'contact_id' => 21,
				'name' => 'Lima Websites',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 80,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '6912.00',
				'estimated_development_time' => 80,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:53:27',
				'updated_at' => '2014-04-09 14:53:27',
			),
			15 => 
			array (
				'id' => 17,
				'client_id' => 11,
				'contact_id' => 22,
				'name' => 'Siltuximab 1',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '6048.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:57:53',
				'updated_at' => '2014-04-09 14:57:53',
			),
			16 => 
			array (
				'id' => 18,
				'client_id' => 11,
				'contact_id' => 22,
				'name' => 'Siltuximab 2',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '6048.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:58:09',
				'updated_at' => '2014-04-09 14:58:09',
			),
			17 => 
			array (
				'id' => 19,
				'client_id' => 11,
				'contact_id' => 22,
				'name' => 'Siltuximab 3',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '6912.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:58:34',
				'updated_at' => '2014-04-09 14:58:34',
			),
			18 => 
			array (
				'id' => 20,
				'client_id' => 11,
				'contact_id' => 22,
				'name' => 'Siltuximab 4',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '3744.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:58:56',
				'updated_at' => '2014-04-09 14:58:56',
			),
			19 => 
			array (
				'id' => 22,
				'client_id' => 11,
				'contact_id' => 22,
				'name' => 'Imbruvica 2',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '8064.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 14:59:55',
				'updated_at' => '2014-04-09 14:59:55',
			),
			20 => 
			array (
				'id' => 23,
				'client_id' => 4,
				'contact_id' => 6,
				'name' => 'Extramile YouTube',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 100,
				'resource' => NULL,
				'phase_id' => 7,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '6336.00',
				'estimated_development_time' => 40,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 15:01:10',
				'updated_at' => '2014-04-10 13:29:32',
			),
			21 => 
			array (
				'id' => 24,
				'client_id' => 1,
				'contact_id' => 23,
				'name' => 'Sky Bundle App',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 50,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '29376.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 15:04:41',
				'updated_at' => '2014-04-09 15:04:41',
			),
			22 => 
			array (
				'id' => 25,
				'client_id' => 12,
				'contact_id' => 10,
				'name' => 'Hosting',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 50,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '1822.80',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 15:05:22',
				'updated_at' => '2014-04-09 15:05:22',
			),
			23 => 
			array (
				'id' => 26,
				'client_id' => 13,
				'contact_id' => 14,
				'name' => 'Wordpress Update',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 50,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '2484.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 15:06:12',
				'updated_at' => '2014-04-09 15:06:12',
			),
			24 => 
			array (
				'id' => 27,
				'client_id' => 2,
				'contact_id' => 24,
				'name' => 'Start JG Phase II Updates',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 75,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => '900',
				'estimate_link' => 'https://diginutltd.freeagent.com/estimates/562618',
				'estimate_phase' => NULL,
				'value' => '8064.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 15:06:45',
				'updated_at' => '2014-04-10 13:42:47',
			),
			25 => 
			array (
				'id' => 28,
				'client_id' => 16,
				'contact_id' => 16,
				'name' => 'Cavo Alkyoni Website',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '1890.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-09 15:08:30',
				'updated_at' => '2014-04-09 15:08:30',
			),
			26 => 
			array (
				'id' => 29,
				'client_id' => 5,
				'contact_id' => 7,
				'name' => 'Coppafeel SMS sign up updates',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 50,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '880.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 09:24:22',
				'updated_at' => '2014-04-10 09:24:22',
			),
			27 => 
			array (
				'id' => 30,
				'client_id' => 3,
				'contact_id' => 4,
				'name' => 'Nissan FPS HTML Email',
				'start_date' => NULL,
				'due_date' => '2014-05-05',
				'golive_date' => '2014-05-08',
				'likelihood' => 100,
				'resource' => NULL,
				'phase_id' => 3,
				'percentage_complete' => 0,
				'estimate_number' => '894',
				'estimate_link' => 'https://diginutltd.freeagent.com/estimates/554713',
				'estimate_phase' => NULL,
				'value' => '2700.00',
				'estimated_development_time' => 45,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 09:26:24',
				'updated_at' => '2014-04-22 08:24:51',
			),
			28 => 
			array (
				'id' => 31,
				'client_id' => 17,
				'contact_id' => 17,
				'name' => 'Mobile Website & App',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '55000.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 09:26:56',
				'updated_at' => '2014-04-10 09:26:56',
			),
			29 => 
			array (
				'id' => 32,
				'client_id' => 2,
				'contact_id' => 18,
				'name' => 'Adidas CRP Site amends',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 50,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => '895',
				'estimate_link' => 'https://diginutltd.freeagent.com/estimates/557153',
				'estimate_phase' => NULL,
				'value' => '7632.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 09:27:38',
				'updated_at' => '2014-04-10 09:27:38',
			),
			30 => 
			array (
				'id' => 33,
				'client_id' => 11,
				'contact_id' => 25,
				'name' => 'Vfend iRep Detail Aid',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 60,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '8400.00',
				'estimated_development_time' => 160,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 09:28:03',
				'updated_at' => '2014-04-10 09:30:46',
			),
			31 => 
			array (
				'id' => 34,
				'client_id' => 19,
				'contact_id' => 19,
				'name' => 'IOVOX Reseller Platform',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 50,
			'resource' => 'Pete (FE), Simon (BE), Anh',
				'phase_id' => 3,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '10980.00',
				'estimated_development_time' => 160,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 09:29:23',
				'updated_at' => '2014-04-17 10:31:51',
			),
			32 => 
			array (
				'id' => 35,
				'client_id' => 18,
				'contact_id' => 20,
				'name' => 'Interim Design Refresh',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '5472.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 09:29:53',
				'updated_at' => '2014-04-10 09:29:53',
			),
			33 => 
			array (
				'id' => 36,
				'client_id' => 20,
				'contact_id' => 26,
				'name' => 'Brand App',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '10000.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-10 12:38:45',
				'updated_at' => '2014-04-17 15:13:22',
			),
			34 => 
			array (
				'id' => 38,
				'client_id' => 1,
				'contact_id' => 23,
				'name' => 'Golden Toaster Newsletter Form',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '1008.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-16 15:32:55',
				'updated_at' => '2014-04-16 15:32:55',
			),
			35 => 
			array (
				'id' => 39,
				'client_id' => 21,
				'contact_id' => 27,
				'name' => 'Facebook / Twitter Sharing Tool ',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => NULL,
				'resource' => NULL,
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => NULL,
				'estimate_link' => NULL,
				'estimate_phase' => NULL,
				'value' => '3168.00',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-16 15:33:29',
				'updated_at' => '2014-04-17 15:13:01',
			),
			36 => 
			array (
				'id' => 40,
				'client_id' => 5,
				'contact_id' => 7,
				'name' => 'Coppafeel Shop Page Update',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => '2014-05-02',
				'likelihood' => 50,
			'resource' => 'Simon (BE)',
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => '905',
				'estimate_link' => 'https://diginutltd.freeagent.com/estimates/571582',
				'estimate_phase' => 'Estimate',
				'value' => '842.40',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-22 09:52:42',
				'updated_at' => '2014-04-22 10:07:55',
			),
			37 => 
			array (
				'id' => 41,
				'client_id' => 3,
				'contact_id' => 4,
			'name' => 'Nissan Trade Campaign (May to September) Emails x 3 - Remanufactured Exchange Parts',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 75,
			'resource' => 'Simon (BE), Danny',
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => '907',
				'estimate_link' => 'https://diginutltd.freeagent.com/estimates/571628',
				'estimate_phase' => 'Estimate',
				'value' => '379.99',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-22 11:04:04',
				'updated_at' => '2014-04-22 12:41:01',
			),
			38 => 
			array (
				'id' => 42,
				'client_id' => 3,
				'contact_id' => 4,
			'name' => 'Nissan Trade Campaign (May to September) Emails x 3 - Genuine Parts',
				'start_date' => NULL,
				'due_date' => NULL,
				'golive_date' => NULL,
				'likelihood' => 75,
			'resource' => 'Simon (BE), Danny',
				'phase_id' => 1,
				'percentage_complete' => 0,
				'estimate_number' => '906',
				'estimate_link' => 'https://diginutltd.freeagent.com/estimates/571625',
				'estimate_phase' => 'Estimate',
				'value' => '379.99',
				'estimated_development_time' => NULL,
				'actual_development_time' => NULL,
				'completed_date' => NULL,
				'created_at' => '2014-04-22 11:04:59',
				'updated_at' => '2014-04-22 12:40:56',
			),
		));
	}

}
